# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- develop
- homolog

pool:
  name: 'EOSSRV016'
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- checkout: self
  persistCredentials: true

- task: UseDotNet@2
  displayName: 'Selecting SDK'
  inputs:
    packageType: 'sdk'
    version: '6.0.x'

- task: DotNetCoreCLI@2
  displayName: 'Restoring'
  inputs:
    command: 'restore'
    feedsToUse: 'select'

- task: DotNetCoreCLI@2
  displayName: 'Building'
  inputs:
    command: 'publish'
    configuration: 'release'
    publishWebProjects: true
    zipAfterPublish: false

- task: PublishBuildArtifacts@1
  displayName: 'Artefato'
  inputs:
    PathtoPublish: 'C:\azure-agente\_work\20\s\bin\Debug\net6.0\publish\'
    ArtifactName: 'PocAzureArtefato'
    publishLocation: 'Container'
